apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: url-redirector
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - "my.host.com"
    secretName: letsencrypt-prod
  rules:
  - host: my.host.com
    http:
      paths:
      - path: /
        backend:
          serviceName: url-redirector
          servicePort: 8080
