apiVersion: serving.knative.dev
kind: Service
metadata:
  name: url-redirector
spec:
  template:
    spec:
      containers:
      - name: url-redirector
        image: registry.gitlab.com/bobymcbobs/url-redirector:latest
        ports:
          - containerPort: 8080
        env:
          - name: TZ
            value: "Pacific/Auckland"
          - name: APP_CONFIG_YAML
            value: /app/cfg/config.yaml
        volumeMounts:
          - name: url-redirector-data
            mountPath: /app/cfg
      volumes:
        - name: url-redirector-data
          configMap:
            name: url-redirector-data
            items:
              - key: config.yaml
                path: config.yaml
